# JWT Configuration
jwt:
  secret: 2?Q:mba;7mvN[^0=Ixw54z@YOiySC!TqGF)-20tOL`*qs^AlK_|gYoS;ah0r2Oj
  expiration: 900_000 # 15 minutes
  issuer: 'MrFullStack'
  audience: Portfolio APP
  prefix: 'Bearer '
  excluded.urls: > 
    /homepage/**,
    /user/login,
    /user/signup,
    /user/reset/*,
    /test/**,
    /error,
    
# Client Configuration  
client:
  url: http://localhost:3000 
  email:
    verify: 
      param: user/verifyEmail
      expiration: 86_400_000 # 24 hours
    reset: 
      param: user/resetPassword
      expiration: 600_000 # 10 minutes 

# Globals:
# Api:
#   Cors:
#     AllowMethods: "'OPTIONS, POST, GET, DELETE, PUT'"
#     AllowHeaders: "'*'"
#     AllowOrigin: "'localhost:8089'"

# # configuration
# config:
#   json_location: ${file(./config.json):PATH}
      